name: Dataset Pull Automation

on:
  workflow_dispatch:
  
  schedule:
    - cron: '0 8 * * *'


jobs:
  PULLDATASET:
    runs-on: ubuntu-latest
    env:
      working-directory: ./CKANOpenDataImport
    defaults:
      run:
        working-directory: .

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
          python-version: '3.9'
    - name: Run Script arcgis.py
      run: python arcgis.py
    - name: Run Script py_USMART_import/Import_DCAT.ipynb
      run: python py_USMART_import/Import_DCAT.ipynb
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore ./CKANOpenDataImport/CKANOpenDataImport.csproj
    - name: Build
      run: dotnet build ./CKANOpenDataImport/CKANOpenDataImport.csproj --no-restore
    - name: Run
      working-directory: ${{ env.working-directory  }}
      run: dotnet run
    - name: Copy output to folder
      run: cp ./CKANOpenDataImport/ckan_output.csv ./data/ckan_output.csv
    - name: Run Script dcat.py
      run: python dcat.py
    - name: Install dependencies for merge_data.py
      run: python -m pip install pandas markdown pyyaml
    - name: Run Script merge_data.py
      run: python ./merge_data.py
    - name: Run Script export2jkan.py
      run: python ./export2jkan.py
    - name: Git config
      run: |
        git config user.name "GitHub Actions"
        git config user.email "<>"
    - name: Git status
      run: git status
    - name: Commit and push
      run: git add -A && git commit -m "Dataset Pull Automatic Trigger" && git push origin main

